:::::::::::::: Seguimiento de Errores DynamoDB ::::::::::::::
13/09/2017 16:13:38 ==> País: PE - Usuario: 000718734
Error message: Se canceló una tarea.
StackTrace:    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Portal.Consultoras.Common.LogManager.RegistrarDynamoDB(LogError logError) en C:\BELCORP\PortalConsultoras2\app\Portal.Consultoras.Common\LogManager\LogManager.cs:línea 141
Adicional: {"Aplicacion":"PORTALCONSULTORAS","Pais":"PE","Usuario":"000718734","Mensaje":"No había ningún extremo escuchando en http://localhost:23486/ComunidadService.svc que pudiera aceptar el mensaje. La causa suele ser una dirección o una acción SOAP incorrecta. Consulte InnerException, si está presente, para obtener más información., InnerException: No es posible conectar con el servidor remoto, InnerException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión 127.0.0.1:23486","StackTrace":"System.ServiceModel.EndpointNotFoundException: No había ningún extremo escuchando en http://localhost:23486/ComunidadService.svc que pudiera aceptar el mensaje. La causa suele ser una dirección o una acción SOAP incorrecta. Consulte InnerException, si está presente, para obtener más información. ---> System.Net.WebException: No es posible conectar con el servidor remoto ---> System.Net.Sockets.SocketException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión 127.0.0.1:23486\r\n   en System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)\r\n   en System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fin del seguimiento de la pila de la excepción interna ---\r\n   en System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)\r\n   en System.Net.HttpWebRequest.GetRequestStream()\r\n   en System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()\r\n   --- Fin del seguimiento de la pila de la excepción interna ---\r\n\r\nServer stack trace: \r\n   en System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()\r\n   en System.ServiceModel.Channels.HttpOutput.Send(TimeSpan timeout)\r\n   en System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.SendRequest(Message message, TimeSpan timeout)\r\n   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)\r\n   en System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)\r\n   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)\r\n   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)\r\n   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)\r\n\r\nException rethrown at [0]: \r\n   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)\r\n   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)\r\n   en Portal.Consultoras.Web.ServiceComunidad.IComunidadService.GetUsuarioInformacion(BEUsuarioComunidad oBEUsuarioComunidad)\r\n   en Portal.Consultoras.Web.ServiceComunidad.ComunidadServiceClient.GetUsuarioInformacion(BEUsuarioComunidad oBEUsuarioComunidad) en C:\\BELCORP\\PortalConsultoras2\\app\\Portal.Consultoras.Web\\Service References\\ServiceComunidad\\Reference.cs:línea 574\r\n   en Portal.Consultoras.Web.Controllers.LoginController.EsUsuarioComunidad(Int32 PaisId, String CodigoUsuario) en C:\\BELCORP\\PortalConsultoras2\\app\\Portal.Consultoras.Web\\Controllers\\LoginController.cs:línea 1310","Extra":{"Origen":"ServidorWeb","Url":"http://localhost:20267/Login/Login","Browser":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36","TipoTrace":"LogManager","Server":"ZOLUXLP088"}}

:::::::::::::: Seguimiento de Errores DynamoDB ::::::::::::::
13/09/2017 16:55:28 ==> País: PE - Usuario: 000715824
Error message: Se canceló una tarea.
StackTrace:    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Portal.Consultoras.Common.LogManager.RegistrarDynamoDB(LogError logError) en C:\BELCORP\PortalConsultoras2\app\Portal.Consultoras.Common\LogManager\LogManager.cs:línea 141
Adicional: {"Aplicacion":"PORTALCONSULTORAS","Pais":"PE","Usuario":"000715824","Mensaje":"A public action method 'ConsultarEstrategiasOPT' was not found on controller 'Portal.Consultoras.Web.Controllers.OfertasParaTiController'.","StackTrace":"   en System.Web.Mvc.Controller.HandleUnknownAction(String actionName)\r\n   en System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   en System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   en System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__4(IAsyncResult asyncResult, ProcessRequestState innerState)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   en System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result)\r\n   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)","Extra":{"Origen":"ServidorWeb","Url":"http://localhost:20267/OfertasParaTi/ConsultarEstrategiasOPT","Browser":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36","TipoTrace":"LogManager","Server":"ZOLUXLP088"}}

