:::::::::::::: Seguimiento de Errores DynamoDB ::::::::::::::
1/09/2017 11:20:30 a. m. ==> País: PE - Usuario: 041702206
Error message: Error al enviar la solicitud.
StackTrace:    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Portal.Consultoras.Common.LogManager.RegistrarDynamoDB(LogError logError) en E:\GitHub Source\Brench-MC-HD725\PortalConsultoras2\app\Portal.Consultoras.Common\LogManager\LogManager.cs:línea 141
Adicional: {"Aplicacion":"PORTALCONSULTORAS","Pais":"PE","Usuario":"041702206","Mensaje":"Error al enviar la solicitud., InnerException: Se ha terminado la conexión: No se puede establecer una relación de confianza para el canal seguro SSL/TLS., InnerException: El certificado remoto no es válido según el procedimiento de validación.","StackTrace":"System.Net.Http.HttpRequestException: Error al enviar la solicitud. ---> System.Net.WebException: Se ha terminado la conexión: No se puede establecer una relación de confianza para el canal seguro SSL/TLS. ---> System.Security.Authentication.AuthenticationException: El certificado remoto no es válido según el procedimiento de validación.\r\n   en System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)\r\n   en System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)\r\n   en System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)\r\n   --- Fin del seguimiento de la pila de la excepción interna ---\r\n   en System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)\r\n   en System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)\r\n   --- Fin del seguimiento de la pila de la excepción interna ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   en Portal.Consultoras.Web.Controllers.BaseController.RegistrarLogDynamoDB(String aplicacion, String rol, String pantallaOpcion, String opcionAccion) en E:\\GitHub Source\\Brench-MC-HD725\\PortalConsultoras2\\app\\Portal.Consultoras.Web\\Controllers\\BaseController.cs:línea 2103","Extra":{"Origen":"ServidorWeb","Url":"http://localhost:20267/Bienvenida","Browser":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36","TipoTrace":"LogManager","Server":"PE-LPALQ00106"}}

InnerException: Se ha terminado la conexión: No se puede establecer una relación de confianza para el canal seguro SSL/TLS.
InnerException: El certificado remoto no es válido según el procedimiento de validación.
:::::::::::::: Seguimiento de Errores DynamoDB ::::::::::::::
1/09/2017 11:20:40 a. m. ==> País: PE - Usuario: 041702206
Error message: Error al enviar la solicitud.
StackTrace:    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Portal.Consultoras.Common.LogManager.RegistrarDynamoDB(LogError logError) en E:\GitHub Source\Brench-MC-HD725\PortalConsultoras2\app\Portal.Consultoras.Common\LogManager\LogManager.cs:línea 141
Adicional: {"Aplicacion":"PORTALCONSULTORAS","Pais":"PE","Usuario":"041702206","Mensaje":"The parameters dictionary contains a null entry for parameter 'soloCantidad' of non-nullable type 'System.Boolean' for method 'System.Web.Mvc.JsonResult GetResumenCampania(Boolean)' in 'Portal.Consultoras.Web.Controllers.GestionContenidoController'. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter.\r\nNombre del parámetro: parameters","StackTrace":"   en System.Web.Mvc.ActionDescriptor.ExtractParameterFromDictionary(ParameterInfo parameterInfo, IDictionary`2 parameters, MethodInfo methodInfo)\r\n   en System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)\r\n   en System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)\r\n   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__36(IAsyncResult asyncResult, ActionInvocation innerInvokeState)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   en System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3c()\r\n   en System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass45.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3e()\r\n   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass30.<BeginInvokeActionMethodWithFilters>b__2f(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   en System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass1e.<>c__DisplayClass28.<BeginInvokeAction>b__19()\r\n   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass1e.<BeginInvokeAction>b__1b(IAsyncResult asyncResult)","Extra":{"Origen":"ServidorWeb","Url":"http://localhost:20267/GestionContenido/GetResumenCampania?_=1504282839762","Browser":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36","TipoTrace":"LogManager","Server":"PE-LPALQ00106"}}

InnerException: Se ha terminado la conexión: No se puede establecer una relación de confianza para el canal seguro SSL/TLS.
InnerException: El certificado remoto no es válido según el procedimiento de validación.
:::::::::::::: Seguimiento de Errores DynamoDB ::::::::::::::
1/09/2017 11:20:40 a. m. ==> País: PE - Usuario: 041702206
Error message: Error al enviar la solicitud.
StackTrace:    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Portal.Consultoras.Common.LogManager.RegistrarDynamoDB(LogError logError) en E:\GitHub Source\Brench-MC-HD725\PortalConsultoras2\app\Portal.Consultoras.Common\LogManager\LogManager.cs:línea 141
Adicional: {"Aplicacion":"PORTALCONSULTORAS","Pais":"PE","Usuario":"041702206","Mensaje":"The parameters dictionary contains a null entry for parameter 'soloCantidad' of non-nullable type 'System.Boolean' for method 'System.Web.Mvc.JsonResult GetResumenCampania(Boolean)' in 'Portal.Consultoras.Web.Controllers.GestionContenidoController'. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter.\r\nNombre del parámetro: parameters","StackTrace":"   en System.Web.Mvc.ActionDescriptor.ExtractParameterFromDictionary(ParameterInfo parameterInfo, IDictionary`2 parameters, MethodInfo methodInfo)\r\n   en System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)\r\n   en System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)\r\n   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__36(IAsyncResult asyncResult, ActionInvocation innerInvokeState)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   en System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3c()\r\n   en System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass45.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3e()\r\n   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass30.<BeginInvokeActionMethodWithFilters>b__2f(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   en System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass1e.<>c__DisplayClass28.<BeginInvokeAction>b__19()\r\n   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass1e.<BeginInvokeAction>b__1b(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   en System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   en System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   en System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__4(IAsyncResult asyncResult, ProcessRequestState innerState)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   en System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)\r\n   en System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result)\r\n   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)","Extra":{"Origen":"ServidorWeb","Url":"http://localhost:20267/GestionContenido/GetResumenCampania?_=1504282839762","Browser":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36","TipoTrace":"LogManager","Server":"PE-LPALQ00106"}}

InnerException: Se ha terminado la conexión: No se puede establecer una relación de confianza para el canal seguro SSL/TLS.
InnerException: El certificado remoto no es válido según el procedimiento de validación.
:::::::::::::: Seguimiento de Errores DynamoDB ::::::::::::::
1/09/2017 11:23:55 a. m. ==> País: PE - Usuario: 041702206
Error message: Error al enviar la solicitud.
StackTrace:    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Portal.Consultoras.Common.LogManager.RegistrarDynamoDB(LogError logError) en E:\GitHub Source\Brench-MC-HD725\PortalConsultoras2\app\Portal.Consultoras.Common\LogManager\LogManager.cs:línea 141
Adicional: {"Aplicacion":"PORTALCONSULTORAS","Pais":"PE","Usuario":"041702206","Mensaje":"No había ningún extremo escuchando en http://localhost:23486/ComunidadService.svc que pudiera aceptar el mensaje. La causa suele ser una dirección o una acción SOAP incorrecta. Consulte InnerException, si está presente, para obtener más información., InnerException: No es posible conectar con el servidor remoto, InnerException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión 127.0.0.1:23486","StackTrace":"System.ServiceModel.EndpointNotFoundException: No había ningún extremo escuchando en http://localhost:23486/ComunidadService.svc que pudiera aceptar el mensaje. La causa suele ser una dirección o una acción SOAP incorrecta. Consulte InnerException, si está presente, para obtener más información. ---> System.Net.WebException: No es posible conectar con el servidor remoto ---> System.Net.Sockets.SocketException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión 127.0.0.1:23486\r\n   en System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)\r\n   en System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fin del seguimiento de la pila de la excepción interna ---\r\n   en System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)\r\n   en System.Net.HttpWebRequest.GetRequestStream()\r\n   en System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()\r\n   --- Fin del seguimiento de la pila de la excepción interna ---\r\n\r\nServer stack trace: \r\n   en System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()\r\n   en System.ServiceModel.Channels.HttpOutput.Send(TimeSpan timeout)\r\n   en System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.SendRequest(Message message, TimeSpan timeout)\r\n   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)\r\n   en System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)\r\n   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)\r\n   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)\r\n   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)\r\n\r\nException rethrown at [0]: \r\n   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)\r\n   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)\r\n   en Portal.Consultoras.Web.ServiceComunidad.IComunidadService.GetUsuarioInformacion(BEUsuarioComunidad oBEUsuarioComunidad)\r\n   en Portal.Consultoras.Web.ServiceComunidad.ComunidadServiceClient.GetUsuarioInformacion(BEUsuarioComunidad oBEUsuarioComunidad) en E:\\GitHub Source\\Brench-MC-HD725\\PortalConsultoras2\\app\\Portal.Consultoras.Web\\Service References\\ServiceComunidad\\Reference.cs:línea 574\r\n   en Portal.Consultoras.Web.Controllers.LoginController.EsUsuarioComunidad(Int32 PaisId, String CodigoUsuario) en E:\\GitHub Source\\Brench-MC-HD725\\PortalConsultoras2\\app\\Portal.Consultoras.Web\\Controllers\\LoginController.cs:línea 1247","Extra":{"Origen":"ServidorWeb","Url":"http://localhost:20267/Login/Login","Browser":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36","TipoTrace":"LogManager","Server":"PE-LPALQ00106"}}

InnerException: Se ha terminado la conexión: No se puede establecer una relación de confianza para el canal seguro SSL/TLS.
InnerException: El certificado remoto no es válido según el procedimiento de validación.
:::::::::::::: Seguimiento de Errores DynamoDB ::::::::::::::
1/09/2017 11:24:04 a. m. ==> País: PE - Usuario: 041702206
Error message: Error al enviar la solicitud.
StackTrace:    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Portal.Consultoras.Common.LogManager.RegistrarDynamoDB(LogError logError) en E:\GitHub Source\Brench-MC-HD725\PortalConsultoras2\app\Portal.Consultoras.Common\LogManager\LogManager.cs:línea 141
Adicional: {"Aplicacion":"PORTALCONSULTORAS","Pais":"PE","Usuario":"041702206","Mensaje":"Error al enviar la solicitud., InnerException: Se ha terminado la conexión: No se puede establecer una relación de confianza para el canal seguro SSL/TLS., InnerException: El certificado remoto no es válido según el procedimiento de validación.","StackTrace":"System.Net.Http.HttpRequestException: Error al enviar la solicitud. ---> System.Net.WebException: Se ha terminado la conexión: No se puede establecer una relación de confianza para el canal seguro SSL/TLS. ---> System.Security.Authentication.AuthenticationException: El certificado remoto no es válido según el procedimiento de validación.\r\n   en System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)\r\n   en System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)\r\n   en System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)\r\n   --- Fin del seguimiento de la pila de la excepción interna ---\r\n   en System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)\r\n   en System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)\r\n   --- Fin del seguimiento de la pila de la excepción interna ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   en Portal.Consultoras.Web.Controllers.BaseController.RegistrarLogDynamoDB(String aplicacion, String rol, String pantallaOpcion, String opcionAccion) en E:\\GitHub Source\\Brench-MC-HD725\\PortalConsultoras2\\app\\Portal.Consultoras.Web\\Controllers\\BaseController.cs:línea 2103","Extra":{"Origen":"ServidorWeb","Url":"http://localhost:20267/Bienvenida","Browser":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36","TipoTrace":"LogManager","Server":"PE-LPALQ00106"}}

InnerException: Se ha terminado la conexión: No se puede establecer una relación de confianza para el canal seguro SSL/TLS.
InnerException: El certificado remoto no es válido según el procedimiento de validación.
